kumuluzee:
  name: izdelki-service
  version: 1.0.0
  env:
    name: dev
  datasources:
  - jndi-name: jdbc/IzdelkiDS
    #connection-url: jdbc:postgresql://localhost:5432/izdelki
    connection-url: jdbc:postgresql://34.118.85.117:5432/rso
    #connection-url: jdbc:postgresql://host.docker.internal:5432/izdelki
    username: rso
    password: rso