kumuluzee:
  name: izdelki-service
  version: 1.0.0
  env:
    name: dev
  datasources:
  - jndi-name: jdbc/IzdelkiDS
    connection-url: jdbc:postgresql://localhost:5432/izdelki
    #connection-url: jdbc:postgresql://34.118.85.117:5432/rso
    #connection-url: jdbc:postgresql://host.docker.internal:5432/izdelki
    username: rso
    password: rso
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/IzdelkiDS
        type: liveness
      disk-space-health-check:
        threshold: 100000000
  metrics:
    web-instrumentation:
      - name: izdelki-endpoint
        url-pattern: /v1/izdelki/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>

                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="trace" />
                                  </Root>
                              </Loggers>
                          </Configuration>'
  rest-client:
    registrations:
      - class: priljubljeni-izdelki-api
        url: http://localhost:8082/v1
        read-timeout: 3000
rest-properties:
  discount: false
  broken: false
